sudo: false
language: node_js
node_js:
- 0.12.2
install:
- make install
script:
- make test
before_deploy:
- npm-prepublish --verbose
deploy:
  provider: npm
  email: strategic.products@ft.com
  api_key:
    secure: MZf4uiAaiUfVpWEdDgW9ciBTOVDzh77p9KBXDKozGXUJaAciZmvQ04qvDAikEoPNVEevN8WLuszQ1fMlCLHJc/GldViNsgzJCRxfpLkshNvOpReU9qLQsHHOoigu3/++j65k4tZ5FDqObpoW2y5QrKwQ8Zw+eui5Rjl0BA0ihDg1gG7UZniZJxjfOSThWpEQ+kJNJ62Oc+Wkv8JNKIpgadOFWLUc1n59adkY74fm5uOLKJQ5xGVlOdyxzyRLd34FUkKk4JtXmhUzPKTD5J26LzSX/IODwxPhkpETLvY2qEyakDwXfiPEsyr/Yt+Lu5oK7K1V+EcmE89licgSCmGM9xTAJ7KV+dw2G4W9vFVUQGElu8j6dx/b7V2PCH8JmigK17hOhGy40wQS9sYpKZHkfpaePZiMhwDQ3T1h1EQk+ntK9vY299hU7rmEYHxG2hhmA/PeFHvJ5lS30wOS4PikwjPemujk0ltaNMHCc2jzhfLA7rd3vb1qra8B4mmbfOoZpLPD/WU/7REI4cuSr7jM9l6/S1Uhoh1tvgreYQ2UoEKp/tdp29D74Em6UT9HF/5z+p5aWXfAOwoBfZagmyoR+Y8qVJs3vWC9pC4qpk+1Nh0lYJ00atZgXKHsyrz4eQhNP8QxAbxW8MuI1tIVt2PeFEICEDo/zrpkv+yRUU8OS38=
  on:
    tags: true
    repo: Financial-Times/n-eager-fetch
